### ISSUE TITLE
TypeError: (0 , y.getDebugName) is not a function

### ISSUE THREAD

**Issue by charleslouis** [mobxjs/mobx-react-devtools#90]
Hi,

With create-react-app, I have this error when navigating to root url "site/".
`<DevTools />` is called in App.js.

It comes from `node_modules/mobx-react-devtools/index.js:1`

"react": "^16.2.0", 
"mobx": "^3.4.16",
 "mobx-react": "^4.3.5",

Strangely, the `<DevTools />` shows up in site/MyRoute.

Thanks

**Comment by dtouchwyn** [comment]
I'm having the same issue.

**Comment by kristian-puccio** [comment]
I had the same issue and it was fixed by using  version 4.2 of this package.
I suspect that V5 needs mobx V4 to work

**Comment by mweststrate** [comment]
Fixed and released as `mobx-react-devtools@6.0.1`

**Comment by mshibl** [comment]
still getting same issue on version 6.0.2 and mobx version 3.3.0

**Comment by mweststrate** [comment]
Please upgrade MobX to 4 or 5 or downgrade the devtools to v4.

Op za 4 aug. 2018 06:16 schreef Mohamed Shibl <notifications@github.com>:
